### ISSUE TITLE
Нет мануала по установке

### ISSUE THREAD

**Issue by AlexQuaken** [tayanov/Yandex-tts-speechkit-FIX#1]
Можно более подробную инструкцию как воспользоватся.
в HACS не смог найти интеграцию.

**Comment by tayanov** [comment]
В ридми для установки руками все написанно. А через хакс надо скопировать url этого репозитория и добавить в хакс. Тогда он появится в интеграциях Хакса. Если не выйдет пишите. Удачи)

**Comment by AlexQuaken** [comment]
Добавил в HACS поставилось с заменой.
В работу никак не заходит, скопировал из примера в свой конфиг 
tts:
  - platform: yandextts
    api_key: c535432c-e264-4b7e-a8c9-XXXXXXXX
    language: ru-RU
    voice: oksana
    codec: oggopus

ругается на Invalid config for [tts.yandextts]: value is not allowed for dictionary value @ data['codec']. Got 'oggopus'. (See ?, line ?)

Если выбрать голос Alena тоже ругается, api опять устарел ?

**Comment by tayanov** [comment]
Кодек oggopus не доступен в старой интеграции. В той что в комплекте с ха. Попробуйте сначало добавить интеграцию через хакс и сделать ребут. Конфиг ругается на оггопус ввиду проверки конфига по старой интеграции. Можете обращаться за помощью в телеграмм каналы homeassistant. Есть два чата в обоих присутствую и я. Обращайтесь, помогу ...
