### ISSUE TITLE
Через HACS ставится некорректно.

### ISSUE THREAD

**Issue by AlexQuaken** [tayanov/Yandex-tts-speechkit-FIX#2]
Через HACS ставится некорректно.
Создает папку config\custom_components\custom_components\yandextts, сами сами файлы при этом копирует в корень \config\custom_components.
При удалении через HACS удаляет всю папку \config\custom_components целиком со всеми остальными компонентами.
Если ставить руками то все работает корректно.

**Comment by tayanov** [comment]
Fix #2
