### ISSUE TITLE
HACS Default

### ISSUE THREAD

**Issue by wowgamr** [tayanov/Yandex-tts-speechkit-FIX#5]
Классная интеграция, давайте добавим в HACS.

Чек-лист:
- [ ]  Brands https://hacs.xyz/docs/publish/include#check-brands
- [ ]  Manifest.json https://hacs.xyz/docs/publish/include#check-manifest
--> [https://github.com/tayanov/Yandex-tts-speechkit-FIX/pull/6](https://github.com/tayanov/Yandex-tts-speechkit-FIX/pull/6)
- [ ]  Поправить репозиторий https://hacs.xyz/docs/publish/include#check-repository
- [ ]  Тесты от HACS https://hacs.xyz/docs/publish/include#check-hacs
- [ ]  Обновить документацию
- [ ]  Обновить инструкцию по установке

**Comment by wowgamr** [comment]
#6

**Comment by tayanov** [comment]
Интеграция не обновляется. Потому не вижу смысла заводить официально. Как сторонний репозиторий уже сейчас можно добавить в hacs
